# Generated by Django 3.1.2 on 2022-04-19 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WfQualityControlList',
        ),
        migrations.AlterModelOptions(
            name='wfbendingstationlist',
            options={'managed': False, 'verbose_name': 'Станцію гнуття', 'verbose_name_plural': 'Станції гнуття'},
        ),
        migrations.AlterModelOptions(
            name='wfbendlog',
            options={'managed': False, 'verbose_name': 'Лог гнуття', 'verbose_name_plural': 'Логи гнуття'},
        ),
        migrations.AlterModelOptions(
            name='wfconfigurationlist',
            options={'managed': False, 'verbose_name': 'Конфігурацію Топки', 'verbose_name_plural': 'Конфігурації Топок'},
        ),
        migrations.AlterModelOptions(
            name='wfcutlog',
            options={'managed': False, 'verbose_name': 'Лог різки', 'verbose_name_plural': 'Логи різки'},
        ),
        migrations.AlterModelOptions(
            name='wfdfxversioncontrollog',
            options={'managed': False, 'verbose_name': 'Лог DFX Версії', 'verbose_name_plural': 'Логи DFX Версій'},
        ),
        migrations.AlterModelOptions(
            name='wffinalproductlog',
            options={'managed': False, 'verbose_name': 'Лог фінального продукту', 'verbose_name_plural': 'Логи фінального продукту'},
        ),
        migrations.AlterModelOptions(
            name='wffireclaytypelist',
            options={'managed': False, 'verbose_name': 'Тип шамотування', 'verbose_name_plural': 'Типи шамотування'},
        ),
        migrations.AlterModelOptions(
            name='wfframetypelist',
            options={'managed': False, 'verbose_name': 'Тип рами', 'verbose_name_plural': 'Типи рам'},
        ),
        migrations.AlterModelOptions(
            name='wfglasslog',
            options={'managed': False, 'verbose_name': 'Лог скління', 'verbose_name_plural': 'Логи скління'},
        ),
        migrations.AlterModelOptions(
            name='wfglazingtypelist',
            options={'managed': False, 'verbose_name': 'Тип скління', 'verbose_name_plural': 'Типи скління'},
        ),
        migrations.AlterModelOptions(
            name='wfjobstatuslist',
            options={'managed': False, 'verbose_name': 'Статус виконання робіт', 'verbose_name_plural': 'Статуси виконання робіт'},
        ),
        migrations.AlterModelOptions(
            name='wflocksmithlog',
            options={'managed': False, 'verbose_name': 'Лог слюсарні', 'verbose_name_plural': 'Логи слюсарні'},
        ),
        migrations.AlterModelOptions(
            name='wfmodellist',
            options={'managed': False, 'verbose_name': 'Модель Топки', 'verbose_name_plural': 'Моделі Топок'},
        ),
        migrations.AlterModelOptions(
            name='wforderlog',
            options={'managed': False, 'verbose_name': 'Лог Замовлень', 'verbose_name_plural': 'Логи Замовлень'},
        ),
        migrations.AlterModelOptions(
            name='wfpaymentlist',
            options={'managed': False, 'verbose_name': 'Тип олати', 'verbose_name_plural': 'Типи оплати'},
        ),
        migrations.AlterModelOptions(
            name='wfprioritylist',
            options={'managed': False, 'verbose_name': 'Пріоритет', 'verbose_name_plural': 'Пріоритети'},
        ),
        migrations.AlterModelOptions(
            name='wfqualitycontrollog',
            options={'managed': False, 'verbose_name': 'Лог контролю якості', 'verbose_name_plural': 'Логи контролю якості'},
        ),
        migrations.AlterModelOptions(
            name='wfweldingstationlist',
            options={'managed': False, 'verbose_name': 'Станцію зварювання', 'verbose_name_plural': 'Станції зварювання'},
        ),
        migrations.AlterModelOptions(
            name='wfweldlog',
            options={'managed': False, 'verbose_name': 'Лог зварювання', 'verbose_name_plural': 'Логи зварювання'},
        ),
    ]
