# Generated by Django 4.0.4 on 2022-09-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Статус виконання замовлення',
                'verbose_name_plural': 'Статуси виконання замовлень',
                'db_table': 'wf_order_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderStatusList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Статус замовлення',
                'verbose_name_plural': 'Статуси замовлень',
                'db_table': 'wf_order_status_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderWorkStage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_of_execution', models.IntegerField(null=True)),
                ('is_locked', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Стадія замовлення',
                'verbose_name_plural': 'Стадії замовлення',
                'db_table': 'wf_order_work_stage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Лог виробництва',
                'verbose_name_plural': 'Логи виробництва',
                'db_table': 'wf_work_log',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='WfOrderWorkStage',
        ),
        migrations.DeleteModel(
            name='WfStageFinalList',
        ),
        migrations.DeleteModel(
            name='WfWorkLog',
        ),
        migrations.AlterModelOptions(
            name='wfconfigurationlist',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': 'Конфігурацію Топки', 'verbose_name_plural': 'Конфігурації Топок'},
        ),
        migrations.AlterModelOptions(
            name='wffireclaytypelist',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': 'Тип шамотування', 'verbose_name_plural': 'Типи шамотування'},
        ),
        migrations.AlterModelOptions(
            name='wfframetypelist',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': 'Тип рами', 'verbose_name_plural': 'Типи рам'},
        ),
        migrations.AlterModelOptions(
            name='wfglazingtypelist',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': 'Тип скління', 'verbose_name_plural': 'Типи скління'},
        ),
        migrations.AlterModelOptions(
            name='wfmodellist',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': 'Модель Топки', 'verbose_name_plural': 'Моделі Топок'},
        ),
        migrations.AlterModelOptions(
            name='wfpaymentlist',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': 'Тип олати', 'verbose_name_plural': 'Типи оплати'},
        ),
        migrations.AlterModelOptions(
            name='wfprioritylist',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': 'Пріоритет', 'verbose_name_plural': 'Пріоритети'},
        ),
    ]
