# Generated by Django 4.0.4 on 2022-05-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20220419_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='WfAuthUserGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Сферу працівників',
                'verbose_name_plural': 'Сфери працівників',
                'db_table': 'wf_auth_user_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WfUserGroupList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Групу працівників',
                'verbose_name_plural': 'Групи працівників',
                'db_table': 'wf_user_group_list',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='WfBendingStationList',
        ),
        migrations.DeleteModel(
            name='WfWeldingStationList',
        ),
        migrations.AlterModelOptions(
            name='wfdfxversioncontrollog',
            options={'managed': False, 'ordering': ['created_at'], 'verbose_name': 'Лог DFX Версії', 'verbose_name_plural': 'Логи DFX Версій'},
        ),
        migrations.AlterModelOptions(
            name='wforderlog',
            options={'managed': False, 'ordering': ['-created_at'], 'verbose_name': 'Лог Замовлень', 'verbose_name_plural': 'Логи Замовлень'},
        ),
    ]
