# Generated by Django 4.0.4 on 2022-06-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_wfauthusergroup_wfusergrouplist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WfDXFVersionControlLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Лог DXF Версії',
                'verbose_name_plural': 'Логи DXF Версій',
                'db_table': 'wf_dxf_version_control_log',
                'ordering': ['created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WfNoteLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Лог нотатки',
                'verbose_name_plural': 'Логи нотаток',
                'db_table': 'wf_note_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WfOrderWorkStage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Стадія замовлення',
                'verbose_name_plural': 'Стадії замовлення',
                'db_table': 'wf_order_work_stage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WfWorkLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Лог виробництва',
                'verbose_name_plural': 'Логи виробництва',
                'db_table': 'wf_work_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WfWorkStageList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'wf_work_stage_list',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='WfDFXVersionControlLog',
        ),
        migrations.DeleteModel(
            name='WfStageSemiFinishedList',
        ),
    ]
