# Generated by Django 4.0.4 on 2022-08-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_wfdxfversioncontrollog_wfnotelog_wforderworkstage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WfBendLog',
        ),
        migrations.DeleteModel(
            name='WfCutLog',
        ),
        migrations.DeleteModel(
            name='WfDXFVersionControlLog',
        ),
        migrations.DeleteModel(
            name='WfGlassLog',
        ),
        migrations.DeleteModel(
            name='WfLocksmithLog',
        ),
        migrations.DeleteModel(
            name='WfQualityControlLog',
        ),
        migrations.DeleteModel(
            name='WfUserGroupList',
        ),
        migrations.DeleteModel(
            name='WfWeldLog',
        ),
        migrations.AlterModelOptions(
            name='wffinalproductlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='wfworkstagelist',
            options={'managed': False, 'verbose_name': 'Стадію виконання роботи', 'verbose_name_plural': 'Стадії виконання роботи'},
        ),
    ]
