# Generated by Django 4.0.4 on 2022-08-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_delete_wfbendlog_delete_wfcutlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.TextField(blank=True, null=True)),
                ('mobile_number', models.TextField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('start_manufacturing', models.BooleanField(default=False)),
                ('start_manufacturing_semi_finished', models.BooleanField(default=True)),
                ('is_canceled', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('deadline_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Лог Замовлень',
                'verbose_name_plural': 'Логи Замовлень',
                'db_table': 'wf_order_log',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='WfOrderLog',
        ),
    ]
