version: '3'

services:

  backend: # GnS application
    restart: unless-stopped
    env_file:
      - ./.envs/.local/.backend
      - ./.envs/.local/.db
    command: /start
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./compose/local/backend/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"


  db: # GnS database.
    build:
      context: .
      dockerfile: ./compose/local/db/Dockerfile
    restart: unless-stopped
    command: --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    ports:
      - "3306:3306"
    env_file:
      - ./.envs/.local/.db
    volumes:
      - db:/var/lib/mysql
      - ./db/backups:/backups

volumes:
  db:
